# Generated by Django 4.2.1 on 2023-06-04 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Documento_Identidad',
            fields=[
                ('tipo_documento_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('tipo_documento_nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tipo_documento_identidad',
            },
        ),
        migrations.CreateModel(
            name='tipos_seguro',
            fields=[
                ('tipo_seguro_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('tipo_seguro_nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tipos_seguro',
            },
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_documento', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_documento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica_list.tipo_documento_identidad')),
                ('tipo_seguro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica_list.tipos_seguro')),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
    ]
